spring.application.name=cinezone
spring.datasource.url=jdbc:postgresql://ep-lively-moon-ajv7wquu-pooler.c-3.us-east-2.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_wqy0ivcI6MeG
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true

# Redis Configuration
spring.data.redis.host=actor-cordial-spiffy-62723.db.redis.io
spring.data.redis.port=12500
spring.data.redis.password=sses7Ao7m8Xu4LJMWT4EGvrT2GaIQI7p

# Cloudinary Configuration
cloudinary.url=cloudinary://714921591663168:mCbnKuIs4ncaVECTyOfm0U9NU5M@dxrokirch

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cinezoneperu@gmail.com
spring.mail.password=wlsleirraummmwov
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# File Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

jwt.secret=4f8b9e6a1c5d2e7f3a0b8c9d4e1f6a2b5c8d3e7f9a1b4c6d0e2f5a8b9c1d3e4f
cors.allowed-origins=https://cinezone-coral.vercel.app
