
    create table asientos (
        en_mantenimiento boolean default false not null,
        fila char(1) not null,
        grid_col integer,
        grid_row integer,
        numero integer not null,
        id bigint generated by default as identity,
        sala_id bigint not null,
        tipo varchar(20) not null check (tipo in ('ESTANDAR','VIP','DISCAPACIDAD')),
        primary key (id),
        unique (sala_id, fila, numero)
    );

    create table audit_logs (
        entity_id bigint not null,
        id bigint generated by default as identity,
        timestamp timestamp(6) not null,
        action varchar(255) not null,
        details TEXT,
        entity_name varchar(255) not null,
        modified_by varchar(255) not null,
        primary key (id)
    );

    create table beneficios_pendientes (
        fecha_expiracion timestamp(6),
        fecha_ganado timestamp(6),
        id bigint generated by default as identity,
        usuario_id uuid not null,
        estado varchar(20) not null check (estado in ('DISPONIBLE','USADO','EXPIRADO')),
        tipo_beneficio varchar(50) not null,
        descripcion varchar(255),
        primary key (id)
    );

    create table benefit_monthly_usage (
        anio integer not null,
        mes integer not null,
        usos integer not null,
        beneficio_id bigint not null,
        id bigint generated by default as identity,
        cliente_id uuid not null,
        primary key (id),
        constraint uk_bmu_cliente_beneficio_fecha unique (cliente_id, beneficio_id, mes, anio)
    );

    create table boleta_asiento (
        precio_pagado numeric(10,2) not null,
        asiento_id bigint not null,
        beneficio_id bigint,
        fecha_validacion timestamp(6),
        id bigint generated by default as identity,
        conadis_dni varchar(15),
        boleta_id uuid not null,
        validador_id uuid,
        estado varchar(20) check (estado in ('PENDIENTE','USADA','CANCELADA')),
        tipo_entrada varchar(20) not null check (tipo_entrada in ('NORMAL','TERCERA_EDAD','DISCAPACIDAD','NINO','BENEFICIO')),
        conadis_ruid varchar(50),
        primary key (id),
        unique (boleta_id, asiento_id)
    );

    create table boleta_dulceria (
        cantidad integer not null,
        entregado boolean not null,
        precio_total numeric(10,2) not null,
        precio_unitario numeric(10,2) not null,
        id bigint generated by default as identity,
        producto_id bigint not null,
        boleta_id uuid not null,
        primary key (id)
    );

    create table boletas (
        monto_total numeric(10,2) not null,
        fecha_compra timestamp(6),
        funcion_id bigint,
        codigo_unico uuid not null unique,
        empleado_id uuid,
        id uuid not null,
        usuario_id uuid,
        estado varchar(20) not null check (estado in ('PENDIENTE','VALIDA','USADA','CANCELADA')),
        metodo_pago varchar(20),
        observaciones TEXT,
        primary key (id)
    );

    create table caja_turnos (
        descuadre numeric(10,2),
        monto_apertura numeric(10,2) not null,
        monto_declarado numeric(10,2),
        monto_esperado numeric(10,2),
        abierto_en timestamp(6) not null,
        cerrado_en timestamp(6),
        id bigint generated by default as identity,
        usuario_id uuid not null,
        estado varchar(20) not null check (estado in ('ABIERTA','CERRADA')),
        modulo varchar(50),
        primary key (id)
    );

    create table combo_detalle (
        cantidad integer not null,
        combo_id bigint not null,
        id bigint generated by default as identity,
        item_producto_id bigint not null,
        primary key (id)
    );

    create table combo_recipes (
        cantidad integer not null,
        is_active boolean not null,
        combo_id bigint not null,
        id bigint generated by default as identity,
        insumo_id bigint not null,
        primary key (id)
    );

    create table funciones (
        activa boolean,
        precio_multiplicador numeric(5,2),
        fecha_hora timestamp(6) not null,
        id bigint generated by default as identity,
        pelicula_id bigint not null,
        sala_id bigint not null,
        sede_id bigint not null,
        formato_proyeccion varchar(20) not null check (formato_proyeccion in ('FORMAT_2D','FORMAT_3D','IMAX','FORMAT_4DX')),
        idioma varchar(50) check (idioma in ('ESPANOL','SUBTITULADA','INGLES_DOBLADO')),
        primary key (id)
    );

    create table movimientos_inventario (
        cantidad integer not null,
        stock_resultante integer not null,
        creado_en timestamp(6) not null,
        id bigint generated by default as identity,
        producto_id bigint not null,
        sede_id bigint not null,
        usuario_id uuid not null,
        tipo_movimiento varchar(20) not null check (tipo_movimiento in ('ENTRADA','SALIDA')),
        motivo varchar(255),
        primary key (id)
    );

    create table niveles_tarjeta (
        consumo_minimo_dulceria numeric(10,2) default 0.00,
        max_entradas_mensuales integer,
        puntos_minimos integer default 0,
        visitas_requeridas_anuales integer not null,
        fecha_actualizacion timestamp(6),
        id_nivel bigint generated by default as identity,
        nombre varchar(50) not null unique,
        descripcion TEXT,
        beneficios jsonb not null,
        primary key (id_nivel)
    );

    create table pelicula_sedes (
        cinema_id bigint not null,
        fecha_asignacion timestamp(6) not null,
        id bigint generated by default as identity,
        movie_id bigint not null,
        primary key (id)
    );

    create table peliculas (
        duracion_minutos integer not null,
        fecha_estreno date,
        fecha_fin_cartelera date,
        id bigint generated by default as identity,
        clasificacion varchar(20),
        estado varchar(20) not null check (estado in ('EN_CARTELERA','PROXIMAMENTE','PRE_VENTA','RETIRADA')),
        idioma varchar(50) check (idioma in ('ESPANOL','SUBTITULADA','INGLES_DOBLADO')),
        genero varchar(100),
        titulo varchar(200) not null,
        poster_url varchar(255),
        sinopsis TEXT,
        trailer_url varchar(255),
        primary key (id)
    );

    create table productos (
        disponible boolean,
        es_insumo boolean,
        precio numeric(10,2) not null,
        precio_puntos integer,
        puntos_otorgados integer,
        cinema_id bigint,
        id bigint generated by default as identity,
        required_tier_id bigint,
        categoria varchar(20) not null check (categoria in ('BEBIDA','SNACK','DULCE','POP_CORN','COMBO','OTROS','INSUMO','ENTRADA')),
        nombre varchar(100) not null,
        descripcion TEXT,
        imagen varchar(255),
        primary key (id)
    );

    create table productos_stock (
        is_active boolean default true not null,
        precio_local numeric(10,2),
        stock integer not null,
        id bigint generated by default as identity,
        producto_id bigint not null,
        sede_id bigint not null,
        primary key (id),
        unique (producto_id, sede_id)
    );

    create table puntos_historial (
        puntos integer not null,
        fecha timestamp(6),
        id bigint generated by default as identity,
        boleta_id uuid,
        usuario_id uuid not null,
        tipo varchar(20) not null check (tipo in ('GANADO','CANJEADO')),
        descripcion varchar(255) not null,
        primary key (id)
    );

    create table reclamos (
        fecha_reclamo timestamp(6) not null,
        fecha_respuesta timestamp(6),
        id bigint generated by default as identity,
        sede_id bigint,
        detalle varchar(1000) not null,
        email varchar(255) not null,
        estado varchar(255) not null,
        nombre_completo varchar(255) not null,
        numero_documento varchar(255) not null,
        respuesta_admin TEXT,
        telefono varchar(255) not null,
        tipo_documento varchar(255) not null,
        tipo_reclamo varchar(255) not null,
        primary key (id)
    );

    create table replacement_request (
        requested_quantity integer,
        cinema_id bigint,
        created_at timestamp(6),
        id bigint generated by default as identity,
        product_id bigint,
        status varchar(255),
        primary key (id)
    );

    create table salas (
        activa boolean,
        capacidad_total integer not null,
        id bigint generated by default as identity,
        sede_id bigint not null,
        tipo varchar(30),
        nombre varchar(50) not null,
        primary key (id)
    );

    create table security_audit (
        id bigint generated by default as identity,
        timestamp timestamp(6),
        correo_intentado varchar(255),
        evento varchar(255),
        ip varchar(255),
        primary key (id)
    );

    create table sedes (
        activa boolean,
        id bigint generated by default as identity,
        ciudad varchar(100) not null,
        nombre varchar(100) not null,
        imagen varchar(500),
        direccion varchar(255) not null,
        primary key (id)
    );

    create table sesion_compra (
        fecha_inicio timestamp(6),
        funcion_id bigint,
        ultima_modificacion timestamp(6),
        id uuid not null,
        usuario_id uuid,
        estado varchar(20) not null check (estado in ('EN_PROCESO','COMPLETADA','ABANDONADA')),
        primary key (id)
    );

    create table system_alerts (
        leido boolean not null,
        fecha_creacion timestamp(6) not null,
        replacement_request_id bigint,
        sede_id bigint not null,
        id uuid not null,
        emisor_email varchar(255) not null,
        mensaje TEXT not null,
        receptor_rol varchar(255) not null,
        tipo_alerta varchar(255) not null,
        primary key (id)
    );

    create table ticket_base_prices_v2 (
        base_price numeric(10,2) not null,
        is_active boolean not null,
        price_friday numeric(10,2),
        price_monday numeric(10,2),
        price_saturday numeric(10,2),
        price_sunday numeric(10,2),
        price_thursday numeric(10,2),
        price_tuesday numeric(10,2),
        price_wednesday numeric(10,2),
        beneficio_id bigint,
        id bigint generated by default as identity,
        ticket_type varchar(20) not null check (ticket_type in ('NORMAL','TERCERA_EDAD','DISCAPACIDAD','NINO','BENEFICIO')),
        formato varchar(50),
        name varchar(100) not null,
        primary key (id),
        unique (ticket_type, formato, beneficio_id)
    );

    create table ticket_benefits (
        limite_mensual integer,
        points_required integer,
        price numeric(10,2) not null,
        ticket_count integer,
        id bigint generated by default as identity,
        ticket_base_price_id bigint,
        tier_id bigint not null,
        formato varchar(50),
        name varchar(255) not null,
        primary key (id)
    );

    create table ticket_type_sede_prices_v2 (
        is_active boolean not null,
        local_price numeric(10,2) not null,
        price_friday numeric(10,2),
        price_monday numeric(10,2),
        price_saturday numeric(10,2),
        price_sunday numeric(10,2),
        price_thursday numeric(10,2),
        price_tuesday numeric(10,2),
        price_wednesday numeric(10,2),
        id bigint generated by default as identity,
        sede_id bigint not null,
        ticket_base_price_id bigint not null,
        primary key (id),
        unique (sede_id, ticket_base_price_id)
    );

    create table usuario_sedes (
        sede_id bigint not null,
        usuario_id uuid not null,
        primary key (sede_id, usuario_id)
    );

    create table usuarios (
        activo boolean,
        consumo_anual_dulceria numeric(10,2),
        es_socio boolean,
        fecha_inicio_periodo date,
        fecha_nacimiento date,
        fecha_ultima_visita date,
        mes_ultimo_beneficio integer,
        puntos integer,
        tiene_discapacidad boolean,
        verification_attempts integer,
        yearly_visits integer,
        fecha_registro timestamp(6),
        nivel_id bigint,
        verification_expiry timestamp(6),
        dni varchar(15) unique,
        id uuid not null,
        celular varchar(20),
        genero varchar(20),
        rol varchar(20) not null check (rol in ('CLIENT','SUPER_ADMIN','ADMIN_SEDE','JEFE_SALA','STAFF','TAQUILLA','DULCERIA','PORTERO','SOPORTE')),
        tipo_documento varchar(20),
        apellido varchar(100) not null,
        nombre varchar(100) not null,
        correo varchar(150) not null unique,
        contrasena varchar(255) not null,
        session_token varchar(255),
        verification_code_hash varchar(255),
        uso_beneficios_mensual jsonb,
        primary key (id)
    );

    alter table if exists asientos 
       add constraint FKacacngne5rjhq9rsmr6fhwlxc 
       foreign key (sala_id) 
       references salas;

    alter table if exists beneficios_pendientes 
       add constraint FKforgxofadh3crlat0nh1kt85a 
       foreign key (usuario_id) 
       references usuarios;

    alter table if exists benefit_monthly_usage 
       add constraint FK8qhbwt0nf7wxa7uwbm1205ap1 
       foreign key (beneficio_id) 
       references ticket_benefits;

    alter table if exists benefit_monthly_usage 
       add constraint FK6b5f83pooq2hjv6jnhi05g5b 
       foreign key (cliente_id) 
       references usuarios;

    alter table if exists boleta_asiento 
       add constraint FKbph5k95q7pp45tdf2aindk9km 
       foreign key (boleta_id) 
       references boletas;

    alter table if exists boleta_asiento 
       add constraint FKg8p4b071s31x4fbxykvjlq082 
       foreign key (asiento_id) 
       references asientos;

    alter table if exists boleta_asiento 
       add constraint FKgf9y13sf70a39tkdjl68ie65t 
       foreign key (validador_id) 
       references usuarios;

    alter table if exists boleta_dulceria 
       add constraint FK9csq0shurmhid2pqxwgsvw71 
       foreign key (boleta_id) 
       references boletas;

    alter table if exists boleta_dulceria 
       add constraint FKp54ie40c0okxd0bi7x4pk6bw0 
       foreign key (producto_id) 
       references productos;

    alter table if exists boletas 
       add constraint FKaed75ejob19iadad7rlj6j796 
       foreign key (empleado_id) 
       references usuarios;

    alter table if exists boletas 
       add constraint FK66jxw365pg2286px5jdjeby8g 
       foreign key (funcion_id) 
       references funciones;

    alter table if exists boletas 
       add constraint FKsmgrkynp0wq7fqnbqbwgfsony 
       foreign key (usuario_id) 
       references usuarios;

    alter table if exists caja_turnos 
       add constraint FKfbwnf2vyv8c5061fj2rx1csq 
       foreign key (usuario_id) 
       references usuarios;

    alter table if exists combo_detalle 
       add constraint FKpxikmbe4rb1gdah9wpnhk4f63 
       foreign key (combo_id) 
       references productos;

    alter table if exists combo_detalle 
       add constraint FKte10p1xd6lhncnxj0gflaperb 
       foreign key (item_producto_id) 
       references productos;

    alter table if exists combo_recipes 
       add constraint FK8gekl6ctgh3bbwcd6gt1n7dex 
       foreign key (combo_id) 
       references productos;

    alter table if exists combo_recipes 
       add constraint FK1qwgbor9pbew6xaj1v00b29aq 
       foreign key (insumo_id) 
       references productos;

    alter table if exists funciones 
       add constraint FKjhbrkqo8u9kwtf8gy5deq6605 
       foreign key (sala_id) 
       references salas;

    alter table if exists funciones 
       add constraint FKdi9kw4o3cp35fhl2trcyp6xuy 
       foreign key (sede_id) 
       references sedes;

    alter table if exists funciones 
       add constraint FKqsr9by9n0nifvf4pskpjws7oq 
       foreign key (pelicula_id) 
       references peliculas;

    alter table if exists movimientos_inventario 
       add constraint FK3x0iifxrfesjfkx6o9ptjvmt 
       foreign key (sede_id) 
       references sedes;

    alter table if exists movimientos_inventario 
       add constraint FK36oqksnam23hjdna6ny4oimsm 
       foreign key (producto_id) 
       references productos;

    alter table if exists movimientos_inventario 
       add constraint FKakkxu577al9vljuur2ahk0lo 
       foreign key (usuario_id) 
       references usuarios;

    alter table if exists pelicula_sedes 
       add constraint FK9dn9npu6j8a7rk81p42qil0gj 
       foreign key (cinema_id) 
       references sedes;

    alter table if exists pelicula_sedes 
       add constraint FKpqwvg104c77l1af5w41r2qev1 
       foreign key (movie_id) 
       references peliculas;

    alter table if exists productos 
       add constraint FKgwl7u4xkwkm8bu9h4c0wqsdt0 
       foreign key (cinema_id) 
       references sedes;

    alter table if exists productos 
       add constraint FK3oign80hnjopchmdx7ugtm21d 
       foreign key (required_tier_id) 
       references niveles_tarjeta;

    alter table if exists productos_stock 
       add constraint FK6nndor92qghuoxc527jgtgli4 
       foreign key (sede_id) 
       references sedes;

    alter table if exists productos_stock 
       add constraint FK1jdhowool3em019fp1itrqdoi 
       foreign key (producto_id) 
       references productos;

    alter table if exists puntos_historial 
       add constraint FKi3019qlp5uvphws76tbk4kk78 
       foreign key (boleta_id) 
       references boletas;

    alter table if exists puntos_historial 
       add constraint FKnpy7eoeq68sv0iuj0hpn9gj4u 
       foreign key (usuario_id) 
       references usuarios;

    alter table if exists replacement_request 
       add constraint FK5ygqsswbk4t0u4yqalxrd9sd4 
       foreign key (cinema_id) 
       references sedes;

    alter table if exists replacement_request 
       add constraint FKcnvrnhj00d7s0tpgue1k8jhx7 
       foreign key (product_id) 
       references productos;

    alter table if exists salas 
       add constraint FKh76xpakf0sp2v6u8gqy14kovg 
       foreign key (sede_id) 
       references sedes;

    alter table if exists sesion_compra 
       add constraint FK26xrf7cg4din4x2n3w0m26kpd 
       foreign key (funcion_id) 
       references funciones;

    alter table if exists sesion_compra 
       add constraint FK256tjkyilsuxujkoymh3yc7me 
       foreign key (usuario_id) 
       references usuarios;

    alter table if exists ticket_base_prices_v2 
       add constraint FKs02o7q2yrkbdmxyp4hkbc3eyk 
       foreign key (beneficio_id) 
       references ticket_benefits;

    alter table if exists ticket_benefits 
       add constraint FKh92l3t26eaeh7c9wtc7cs9kg0 
       foreign key (tier_id) 
       references niveles_tarjeta;

    alter table if exists ticket_type_sede_prices_v2 
       add constraint FK9m9ucck2fl4ukb5yhfet7vknf 
       foreign key (sede_id) 
       references sedes;

    alter table if exists ticket_type_sede_prices_v2 
       add constraint FKso3rfwyjw0j67hee63dcjalut 
       foreign key (ticket_base_price_id) 
       references ticket_base_prices_v2;

    alter table if exists usuario_sedes 
       add constraint FKm0q7yuy8v06j4hxv0ykt17oei 
       foreign key (sede_id) 
       references sedes;

    alter table if exists usuario_sedes 
       add constraint FKdps4qm3pbpmtbcqhnyr66hcu6 
       foreign key (usuario_id) 
       references usuarios;

    alter table if exists usuarios 
       add constraint FK3opebdmu1c22thoypk8tt4ono 
       foreign key (nivel_id) 
       references niveles_tarjeta;

    create table asientos (
        en_mantenimiento boolean default false not null,
        fila char(1) not null,
        grid_col integer,
        grid_row integer,
        numero integer not null,
        id bigint generated by default as identity,
        sala_id bigint not null,
        tipo varchar(20) not null check (tipo in ('ESTANDAR','VIP','DISCAPACIDAD')),
        primary key (id),
        unique (sala_id, fila, numero)
    );

    create table audit_logs (
        entity_id bigint not null,
        id bigint generated by default as identity,
        timestamp timestamp(6) not null,
        action varchar(255) not null,
        details TEXT,
        entity_name varchar(255) not null,
        modified_by varchar(255) not null,
        primary key (id)
    );

    create table beneficios_pendientes (
        fecha_expiracion timestamp(6),
        fecha_ganado timestamp(6),
        id bigint generated by default as identity,
        usuario_id uuid not null,
        estado varchar(20) not null check (estado in ('DISPONIBLE','USADO','EXPIRADO')),
        tipo_beneficio varchar(50) not null,
        descripcion varchar(255),
        primary key (id)
    );

    create table benefit_monthly_usage (
        anio integer not null,
        mes integer not null,
        usos integer not null,
        beneficio_id bigint not null,
        id bigint generated by default as identity,
        cliente_id uuid not null,
        primary key (id),
        constraint uk_bmu_cliente_beneficio_fecha unique (cliente_id, beneficio_id, mes, anio)
    );

    create table boleta_asiento (
        precio_pagado numeric(10,2) not null,
        asiento_id bigint not null,
        beneficio_id bigint,
        fecha_validacion timestamp(6),
        id bigint generated by default as identity,
        conadis_dni varchar(15),
        boleta_id uuid not null,
        validador_id uuid,
        estado varchar(20) check (estado in ('PENDIENTE','USADA','CANCELADA')),
        tipo_entrada varchar(20) not null check (tipo_entrada in ('NORMAL','TERCERA_EDAD','DISCAPACIDAD','NINO','BENEFICIO')),
        conadis_ruid varchar(50),
        primary key (id),
        unique (boleta_id, asiento_id)
    );

    create table boleta_dulceria (
        cantidad integer not null,
        entregado boolean not null,
        precio_total numeric(10,2) not null,
        precio_unitario numeric(10,2) not null,
        id bigint generated by default as identity,
        producto_id bigint not null,
        boleta_id uuid not null,
        primary key (id)
    );

    create table boletas (
        monto_total numeric(10,2) not null,
        fecha_compra timestamp(6),
        funcion_id bigint,
        codigo_unico uuid not null unique,
        empleado_id uuid,
        id uuid not null,
        usuario_id uuid,
        estado varchar(20) not null check (estado in ('PENDIENTE','VALIDA','USADA','CANCELADA')),
        metodo_pago varchar(20),
        observaciones TEXT,
        primary key (id)
    );

    create table caja_turnos (
        descuadre numeric(10,2),
        monto_apertura numeric(10,2) not null,
        monto_declarado numeric(10,2),
        monto_esperado numeric(10,2),
        abierto_en timestamp(6) not null,
        cerrado_en timestamp(6),
        id bigint generated by default as identity,
        usuario_id uuid not null,
        estado varchar(20) not null check (estado in ('ABIERTA','CERRADA')),
        modulo varchar(50),
        primary key (id)
    );

    create table combo_detalle (
        cantidad integer not null,
        combo_id bigint not null,
        id bigint generated by default as identity,
        item_producto_id bigint not null,
        primary key (id)
    );

    create table combo_recipes (
        cantidad integer not null,
        is_active boolean not null,
        combo_id bigint not null,
        id bigint generated by default as identity,
        insumo_id bigint not null,
        primary key (id)
    );

    create table funciones (
        activa boolean,
        precio_multiplicador numeric(5,2),
        fecha_hora timestamp(6) not null,
        id bigint generated by default as identity,
        pelicula_id bigint not null,
        sala_id bigint not null,
        sede_id bigint not null,
        formato_proyeccion varchar(20) not null check (formato_proyeccion in ('FORMAT_2D','FORMAT_3D','IMAX','FORMAT_4DX')),
        idioma varchar(50) check (idioma in ('ESPANOL','SUBTITULADA','INGLES_DOBLADO')),
        primary key (id)
    );

    create table movimientos_inventario (
        cantidad integer not null,
        stock_resultante integer not null,
        creado_en timestamp(6) not null,
        id bigint generated by default as identity,
        producto_id bigint not null,
        sede_id bigint not null,
        usuario_id uuid not null,
        tipo_movimiento varchar(20) not null check (tipo_movimiento in ('ENTRADA','SALIDA')),
        motivo varchar(255),
        primary key (id)
    );

    create table niveles_tarjeta (
        consumo_minimo_dulceria numeric(10,2) default 0.00,
        max_entradas_mensuales integer,
        puntos_minimos integer default 0,
        visitas_requeridas_anuales integer not null,
        fecha_actualizacion timestamp(6),
        id_nivel bigint generated by default as identity,
        nombre varchar(50) not null unique,
        descripcion TEXT,
        beneficios jsonb not null,
        primary key (id_nivel)
    );

    create table pelicula_sedes (
        cinema_id bigint not null,
        fecha_asignacion timestamp(6) not null,
        id bigint generated by default as identity,
        movie_id bigint not null,
        primary key (id)
    );

    create table peliculas (
        duracion_minutos integer not null,
        fecha_estreno date,
        fecha_fin_cartelera date,
        id bigint generated by default as identity,
        clasificacion varchar(20),
        estado varchar(20) not null check (estado in ('EN_CARTELERA','PROXIMAMENTE','PRE_VENTA','RETIRADA')),
        idioma varchar(50) check (idioma in ('ESPANOL','SUBTITULADA','INGLES_DOBLADO')),
        genero varchar(100),
        titulo varchar(200) not null,
        poster_url varchar(255),
        sinopsis TEXT,
        trailer_url varchar(255),
        primary key (id)
    );

    create table productos (
        disponible boolean,
        es_insumo boolean,
        precio numeric(10,2) not null,
        precio_puntos integer,
        puntos_otorgados integer,
        cinema_id bigint,
        id bigint generated by default as identity,
        required_tier_id bigint,
        categoria varchar(20) not null check (categoria in ('BEBIDA','SNACK','DULCE','POP_CORN','COMBO','OTROS','INSUMO','ENTRADA')),
        nombre varchar(100) not null,
        descripcion TEXT,
        imagen varchar(255),
        primary key (id)
    );

    create table productos_stock (
        is_active boolean default true not null,
        precio_local numeric(10,2),
        stock integer not null,
        id bigint generated by default as identity,
        producto_id bigint not null,
        sede_id bigint not null,
        primary key (id),
        unique (producto_id, sede_id)
    );

    create table puntos_historial (
        puntos integer not null,
        fecha timestamp(6),
        id bigint generated by default as identity,
        boleta_id uuid,
        usuario_id uuid not null,
        tipo varchar(20) not null check (tipo in ('GANADO','CANJEADO')),
        descripcion varchar(255) not null,
        primary key (id)
    );

    create table reclamos (
        fecha_reclamo timestamp(6) not null,
        fecha_respuesta timestamp(6),
        id bigint generated by default as identity,
        sede_id bigint,
        detalle varchar(1000) not null,
        email varchar(255) not null,
        estado varchar(255) not null,
        nombre_completo varchar(255) not null,
        numero_documento varchar(255) not null,
        respuesta_admin TEXT,
        telefono varchar(255) not null,
        tipo_documento varchar(255) not null,
        tipo_reclamo varchar(255) not null,
        primary key (id)
    );

    create table replacement_request (
        requested_quantity integer,
        cinema_id bigint,
        created_at timestamp(6),
        id bigint generated by default as identity,
        product_id bigint,
        status varchar(255),
        primary key (id)
    );

    create table salas (
        activa boolean,
        capacidad_total integer not null,
        id bigint generated by default as identity,
        sede_id bigint not null,
        tipo varchar(30),
        nombre varchar(50) not null,
        primary key (id)
    );

    create table security_audit (
        id bigint generated by default as identity,
        timestamp timestamp(6),
        correo_intentado varchar(255),
        evento varchar(255),
        ip varchar(255),
        primary key (id)
    );

    create table sedes (
        activa boolean,
        id bigint generated by default as identity,
        ciudad varchar(100) not null,
        nombre varchar(100) not null,
        imagen varchar(500),
        direccion varchar(255) not null,
        primary key (id)
    );

    create table sesion_compra (
        fecha_inicio timestamp(6),
        funcion_id bigint,
        ultima_modificacion timestamp(6),
        id uuid not null,
        usuario_id uuid,
        estado varchar(20) not null check (estado in ('EN_PROCESO','COMPLETADA','ABANDONADA')),
        primary key (id)
    );

    create table system_alerts (
        leido boolean not null,
        fecha_creacion timestamp(6) not null,
        replacement_request_id bigint,
        sede_id bigint not null,
        id uuid not null,
        emisor_email varchar(255) not null,
        mensaje TEXT not null,
        receptor_rol varchar(255) not null,
        tipo_alerta varchar(255) not null,
        primary key (id)
    );

    create table ticket_base_prices_v2 (
        base_price numeric(10,2) not null,
        is_active boolean not null,
        price_friday numeric(10,2),
        price_monday numeric(10,2),
        price_saturday numeric(10,2),
        price_sunday numeric(10,2),
        price_thursday numeric(10,2),
        price_tuesday numeric(10,2),
        price_wednesday numeric(10,2),
        beneficio_id bigint,
        id bigint generated by default as identity,
        ticket_type varchar(20) not null check (ticket_type in ('NORMAL','TERCERA_EDAD','DISCAPACIDAD','NINO','BENEFICIO')),
        formato varchar(50),
        name varchar(100) not null,
        primary key (id),
        unique (ticket_type, formato, beneficio_id)
    );

    create table ticket_benefits (
        limite_mensual integer,
        points_required integer,
        price numeric(10,2) not null,
        ticket_count integer,
        id bigint generated by default as identity,
        ticket_base_price_id bigint,
        tier_id bigint not null,
        formato varchar(50),
        name varchar(255) not null,
        primary key (id)
    );

    create table ticket_type_sede_prices_v2 (
        is_active boolean not null,
        local_price numeric(10,2) not null,
        price_friday numeric(10,2),
        price_monday numeric(10,2),
        price_saturday numeric(10,2),
        price_sunday numeric(10,2),
        price_thursday numeric(10,2),
        price_tuesday numeric(10,2),
        price_wednesday numeric(10,2),
        id bigint generated by default as identity,
        sede_id bigint not null,
        ticket_base_price_id bigint not null,
        primary key (id),
        unique (sede_id, ticket_base_price_id)
    );

    create table usuario_sedes (
        sede_id bigint not null,
        usuario_id uuid not null,
        primary key (sede_id, usuario_id)
    );

    create table usuarios (
        activo boolean,
        consumo_anual_dulceria numeric(10,2),
        es_socio boolean,
        fecha_inicio_periodo date,
        fecha_nacimiento date,
        fecha_ultima_visita date,
        mes_ultimo_beneficio integer,
        puntos integer,
        tiene_discapacidad boolean,
        verification_attempts integer,
        yearly_visits integer,
        fecha_registro timestamp(6),
        nivel_id bigint,
        verification_expiry timestamp(6),
        dni varchar(15) unique,
        id uuid not null,
        celular varchar(20),
        genero varchar(20),
        rol varchar(20) not null check (rol in ('CLIENT','SUPER_ADMIN','ADMIN_SEDE','JEFE_SALA','STAFF','TAQUILLA','DULCERIA','PORTERO','SOPORTE')),
        tipo_documento varchar(20),
        apellido varchar(100) not null,
        nombre varchar(100) not null,
        correo varchar(150) not null unique,
        contrasena varchar(255) not null,
        session_token varchar(255),
        verification_code_hash varchar(255),
        uso_beneficios_mensual jsonb,
        primary key (id)
    );

    alter table if exists asientos 
       add constraint FKacacngne5rjhq9rsmr6fhwlxc 
       foreign key (sala_id) 
       references salas;

    alter table if exists beneficios_pendientes 
       add constraint FKforgxofadh3crlat0nh1kt85a 
       foreign key (usuario_id) 
       references usuarios;

    alter table if exists benefit_monthly_usage 
       add constraint FK8qhbwt0nf7wxa7uwbm1205ap1 
       foreign key (beneficio_id) 
       references ticket_benefits;

    alter table if exists benefit_monthly_usage 
       add constraint FK6b5f83pooq2hjv6jnhi05g5b 
       foreign key (cliente_id) 
       references usuarios;

    alter table if exists boleta_asiento 
       add constraint FKbph5k95q7pp45tdf2aindk9km 
       foreign key (boleta_id) 
       references boletas;

    alter table if exists boleta_asiento 
       add constraint FKg8p4b071s31x4fbxykvjlq082 
       foreign key (asiento_id) 
       references asientos;

    alter table if exists boleta_asiento 
       add constraint FKgf9y13sf70a39tkdjl68ie65t 
       foreign key (validador_id) 
       references usuarios;

    alter table if exists boleta_dulceria 
       add constraint FK9csq0shurmhid2pqxwgsvw71 
       foreign key (boleta_id) 
       references boletas;

    alter table if exists boleta_dulceria 
       add constraint FKp54ie40c0okxd0bi7x4pk6bw0 
       foreign key (producto_id) 
       references productos;

    alter table if exists boletas 
       add constraint FKaed75ejob19iadad7rlj6j796 
       foreign key (empleado_id) 
       references usuarios;

    alter table if exists boletas 
       add constraint FK66jxw365pg2286px5jdjeby8g 
       foreign key (funcion_id) 
       references funciones;

    alter table if exists boletas 
       add constraint FKsmgrkynp0wq7fqnbqbwgfsony 
       foreign key (usuario_id) 
       references usuarios;

    alter table if exists caja_turnos 
       add constraint FKfbwnf2vyv8c5061fj2rx1csq 
       foreign key (usuario_id) 
       references usuarios;

    alter table if exists combo_detalle 
       add constraint FKpxikmbe4rb1gdah9wpnhk4f63 
       foreign key (combo_id) 
       references productos;

    alter table if exists combo_detalle 
       add constraint FKte10p1xd6lhncnxj0gflaperb 
       foreign key (item_producto_id) 
       references productos;

    alter table if exists combo_recipes 
       add constraint FK8gekl6ctgh3bbwcd6gt1n7dex 
       foreign key (combo_id) 
       references productos;

    alter table if exists combo_recipes 
       add constraint FK1qwgbor9pbew6xaj1v00b29aq 
       foreign key (insumo_id) 
       references productos;

    alter table if exists funciones 
       add constraint FKjhbrkqo8u9kwtf8gy5deq6605 
       foreign key (sala_id) 
       references salas;

    alter table if exists funciones 
       add constraint FKdi9kw4o3cp35fhl2trcyp6xuy 
       foreign key (sede_id) 
       references sedes;

    alter table if exists funciones 
       add constraint FKqsr9by9n0nifvf4pskpjws7oq 
       foreign key (pelicula_id) 
       references peliculas;

    alter table if exists movimientos_inventario 
       add constraint FK3x0iifxrfesjfkx6o9ptjvmt 
       foreign key (sede_id) 
       references sedes;

    alter table if exists movimientos_inventario 
       add constraint FK36oqksnam23hjdna6ny4oimsm 
       foreign key (producto_id) 
       references productos;

    alter table if exists movimientos_inventario 
       add constraint FKakkxu577al9vljuur2ahk0lo 
       foreign key (usuario_id) 
       references usuarios;

    alter table if exists pelicula_sedes 
       add constraint FK9dn9npu6j8a7rk81p42qil0gj 
       foreign key (cinema_id) 
       references sedes;

    alter table if exists pelicula_sedes 
       add constraint FKpqwvg104c77l1af5w41r2qev1 
       foreign key (movie_id) 
       references peliculas;

    alter table if exists productos 
       add constraint FKgwl7u4xkwkm8bu9h4c0wqsdt0 
       foreign key (cinema_id) 
       references sedes;

    alter table if exists productos 
       add constraint FK3oign80hnjopchmdx7ugtm21d 
       foreign key (required_tier_id) 
       references niveles_tarjeta;

    alter table if exists productos_stock 
       add constraint FK6nndor92qghuoxc527jgtgli4 
       foreign key (sede_id) 
       references sedes;

    alter table if exists productos_stock 
       add constraint FK1jdhowool3em019fp1itrqdoi 
       foreign key (producto_id) 
       references productos;

    alter table if exists puntos_historial 
       add constraint FKi3019qlp5uvphws76tbk4kk78 
       foreign key (boleta_id) 
       references boletas;

    alter table if exists puntos_historial 
       add constraint FKnpy7eoeq68sv0iuj0hpn9gj4u 
       foreign key (usuario_id) 
       references usuarios;

    alter table if exists replacement_request 
       add constraint FK5ygqsswbk4t0u4yqalxrd9sd4 
       foreign key (cinema_id) 
       references sedes;

    alter table if exists replacement_request 
       add constraint FKcnvrnhj00d7s0tpgue1k8jhx7 
       foreign key (product_id) 
       references productos;

    alter table if exists salas 
       add constraint FKh76xpakf0sp2v6u8gqy14kovg 
       foreign key (sede_id) 
       references sedes;

    alter table if exists sesion_compra 
       add constraint FK26xrf7cg4din4x2n3w0m26kpd 
       foreign key (funcion_id) 
       references funciones;

    alter table if exists sesion_compra 
       add constraint FK256tjkyilsuxujkoymh3yc7me 
       foreign key (usuario_id) 
       references usuarios;

    alter table if exists ticket_base_prices_v2 
       add constraint FKs02o7q2yrkbdmxyp4hkbc3eyk 
       foreign key (beneficio_id) 
       references ticket_benefits;

    alter table if exists ticket_benefits 
       add constraint FKh92l3t26eaeh7c9wtc7cs9kg0 
       foreign key (tier_id) 
       references niveles_tarjeta;

    alter table if exists ticket_type_sede_prices_v2 
       add constraint FK9m9ucck2fl4ukb5yhfet7vknf 
       foreign key (sede_id) 
       references sedes;

    alter table if exists ticket_type_sede_prices_v2 
       add constraint FKso3rfwyjw0j67hee63dcjalut 
       foreign key (ticket_base_price_id) 
       references ticket_base_prices_v2;

    alter table if exists usuario_sedes 
       add constraint FKm0q7yuy8v06j4hxv0ykt17oei 
       foreign key (sede_id) 
       references sedes;

    alter table if exists usuario_sedes 
       add constraint FKdps4qm3pbpmtbcqhnyr66hcu6 
       foreign key (usuario_id) 
       references usuarios;

    alter table if exists usuarios 
       add constraint FK3opebdmu1c22thoypk8tt4ono 
       foreign key (nivel_id) 
       references niveles_tarjeta;
